[user]
email = "mucinoab@gmail.com"
name = "Bruno A. Muci√±o"

[ui]
default-command = "log"
diff.format = "git"
diff.tool = [ "delta", "$left", "$right" ]

[aliases]
s = ["status"]
e = ["edit"]
d = ["diff"]
f = ["git", "fetch"]
