[[profile]]
name = "laptop"

[[profile.output]]
enable = true
search = ["m=0x0BCA", "s=", "v=BOE"]
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false


[[profile]]
name = "monitor"

[[profile.output]]
enable = false
search = ["m=0x0BCA", "s=", "v=BOE"]
mode = "2256x1504@59.999Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=MG701", "s=0000000000000", "v=GGF"]
mode = "2560x1440@165.007Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false
